server {
  listen 443 ssl;
  server_name dx-phe-result.nthung.vlvn.cf;

  ssl_certificate /etc/nginx/conf.d/dx-phe-result.nthung.vlvn.cf/dx-phe-result.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/dx-phe-result.nthung.vlvn.cf/dx-phe-result.nthung.vlvn.cf.key;

  include shared/ssl.conf;

  access_log /var/log/nginx/dx-phe-result.access.log;

  location / {
    include shared/proxy-header.conf

    proxy_pass http://171.244.48.5;
    proxy_redirect http://171.244.48.5 https://dx-phe-result.nthung.vlvn.cf;
  }
}
