server {
  listen 443 ssl;
  server_name electricity-bills.nthung.vlvn.cf;

  ssl_certificate /etc/nginx/conf.d/electricity-bills.nthung.vlvn.cf/electricity-bills.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/electricity-bills.nthung.vlvn.cf/electricity-bills.nthung.vlvn.cf.key;

  include sites/shared/ssl.conf;

  access_log /var/log/nginx/electricity-bills.access.log;

  location / {
    include sites/shared/proxy-header.conf

    proxy_pass http://18.118.206.111:8080;
    proxy_redirect http://18.118.206.111:8080 https://electricity-bills.nthung.vlvn.cf;
  }
}
