server {
  listen 443 ssl;
  server_name electricity-bills.nthung.vlvn.cf;

  ssl_certificate /etc/nginx/conf.d/electricity-bills.nthung.vlvn.cf/electricity-bills.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/electricity-bills.nthung.vlvn.cf/electricity-bills.nthung.vlvn.cf.key;

  include /etc/nginx/conf.d/sites/shared/ssl.conf;

  access_log /var/log/nginx/electricity-bills.access.log;

  location / {
    include /etc/nginx/conf.d/sites/shared/proxy-header.conf;

    proxy_pass http://electricity-bills:3000;
    proxy_redirect http://electricity-bills:3000 https://electricity-bills.nthung.vlvn.cf;
  }
}
