server {
  listen 443 ssl;
  server_name jenkins.nthung.vlvn.cf;

  ssl_certificate /etc/nginx/conf.d/jenkins.nthung.vlvn.cf/jenkins.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/jenkins.nthung.vlvn.cf/jenkins.nthung.vlvn.cf.key;

  include /etc/nginx/conf.d/sites/shared/ssl.conf;

  access_log /var/log/nginx/jenkins.nthung.vlvn.cf.log;

  location / {
    include /etc/nginx/conf.d/sites/shared/proxy-header.conf;

    proxy_pass http://138.3.210.221:8080;
    proxy_redirect http://138.3.210.221:8080 https://jenkins.nthung.vlvn.cf;
  }
}
