server {
  listen 443 ssl;
  server_name mksmart.nthung.vlvn.cf;

  ssl_certificate /etc/nginx/conf.d/mksmart.nthung.vlvn.cf/mksmart.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/mksmart.nthung.vlvn.cf/mksmart.nthung.vlvn.cf.key;

  include conf.d/sites/shared/ssl.conf;

  access_log /var/log/nginx/mksmart.nthung.vlvn.cf.log;

  location / {
    include conf.d/sites/shared/proxy-header.conf

    proxy_pass http://18.118.206.111:3000;
    proxy_redirect http://18.118.206.111:3000 https://mksmart.nthung.vlvn.cf;
  }
}
