server {
  listen 443 ssl;
  server_name nthung.vlvn.cf;

  ssl_certificate /etc/nginx/conf.d/nthung.vlvn.cf/nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/nthung.vlvn.cf/nthung.vlvn.cf.key;

  include shared/ssl.conf;

  access_log /var/log/nginx/nthung.vlvn.cf.log;

  location / {
    include shared/proxy-header.conf

    proxy_pass http://18.118.206.111:8080;
    proxy_redirect http://18.118.206.111:8080 https://nthung.vlvn.cf;
  }
}
