server {
  listen 443 ssl;
  server_name pan-image.nthung.vlvn.cf;
  client_max_body_size 10M;
  ssl_certificate /etc/nginx/conf.d/pan-image.nthung.vlvn.cf/pan-image.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/pan-image.nthung.vlvn.cf/pan-image.nthung.vlvn.cf.key;

  include /etc/nginx/conf.d/sites/shared/ssl.conf;

  access_log /var/log/nginx/pan-image.nthung.vlvn.cf.log;

  location / {
    include /etc/nginx/conf.d/sites/shared/proxy-header.conf;

    proxy_pass http://localhost:9000;
    proxy_redirect http://localhost:9000 https://pan-image.nthung.vlvn.cf;
  }
}
