server {
  listen 443 ssl;
  server_name pan-school.nthung.vlvn.cf;
  client_max_body_size 10M;
  ssl_certificate /etc/nginx/conf.d/pan-school.nthung.vlvn.cf/pan-school.nthung.vlvn.cf.pem;
  ssl_certificate_key /etc/nginx/conf.d/pan-school.nthung.vlvn.cf/pan-school.nthung.vlvn.cf.key;

  include shared/ssl.conf;

  access_log /var/log/nginx/pan-school.nthung.vlvn.cf.log;

  location / {
    include shared/proxy-header.conf

    proxy_pass http://171.244.48.5;
    proxy_redirect http://171.244.48.5 https://pan-school.nthung.vlvn.cf;
  }
}
