apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
    type: DirectoryOrCreate
  storageClassName: standard
