apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks-app
  template:
    metadata:
      labels:
        app: tasks-app
    spec:
      containers:
        - name: tasks
          image: sunshineaact/k8s-networking-tasks
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks
