apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
        - name: users
          image: sunshineaact/k8s-networking-users
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: auth-service.default
              # value: 10.111.207.69
