apiVersion: v1
kind: Service
metadata:
  name: k8s-second-service
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-second-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
      tier: backend
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
        - name: k8s-first-app
          image: sunshineaact/k8s-first-app
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              # httpHeaders:
              #   - name:
              #     value:
            periodSeconds: 10
            initialDelaySeconds: 3

