apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: host-pv
  resources:
    requests:
      storage: 1Gi
