apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks-api
          image: sunshineaact/kub-dep-tasks:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: mongodb://root:example@mongodb-service:27017/tasks?retryWrites=true&w=majority&authSource=admin
            - name: AUTH_API_ADDRESS
              value: auth-service:3000
