apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-folder
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data
    type: DirectoryOrCreate
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-folder-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: users-folder
  resources:
    requests:
      storage: 1Gi
